#this module is a dummy data generator taht 80% mimic the data generated by the Blickfeld pcd sensor.

import signal
import time
from datetime import datetime
import random # Import for generating random numbers

# from blickfeld_scanner.stream import point_cloud # No longer needed for dummy data

from .kafka import publish_kafka_message
# Only import what's still relevant from config, or remove if not used for dummy
from .config import BLICKFELD_KAFKA_TOPIC, SLEEP_DURATION 


class BlickfeldStreamer:
    def __init__(self):
        self.running = True
        self.sleep = SLEEP_DURATION
        # Handle SIGINT (Ctrl+C) and SIGTERM (system stop)
        signal.signal(signal.SIGINT, self._stop)
        signal.signal(signal.SIGTERM, self._stop)

    def _stop(self, signum, frame):
        print(f"\nSignal {signum} received. Stopping gracefully…")
        self.running = False

    # --- ALTERED: Replaced connect_lidar with dummy_connect ---
    def dummy_connect(self):
        """
        This function replaces connecting to a real LiDAR.
        It simulates a successful connection by returning a placeholder.
        """
        print("Simulating connection to a dummy data source.")
        return True # Return anything that signifies a "connection"

    # --- ALTERED: Replaced retrieve_frame with generate_dummy_frame ---
    def generate_dummy_frame(self, num_points=1000):
        """
        Generates a list of dummy [x, y, z] points.
        Each coordinate is a random float between 0 and 100.
        """
        print(f"Generating {num_points} dummy points...")
        dummy_points = []
        for _ in range(num_points):
            x = round(random.uniform(0.0, 100.0), 3) # Random float for x
            y = round(random.uniform(0.0, 100.0), 3) # Random float for y
            z = round(random.uniform(0.0, 100.0), 3) # Random float for z
            dummy_points.append([x, y, z])
        return dummy_points

    def format_pcd(self, points):
        timestamp = datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]
        header = (
            f"# .PCD v0.7 - Point Cloud Data file format\n"
            f"# TIMESTAMP: {timestamp}\n"
            "VERSION 0.7\nFIELDS x y z\nSIZE 4 4 4\n"
            "TYPE F F F\nCOUNT 1 1 1\n"
            f"WIDTH {len(points)}\nHEIGHT 1\n"
            "VIEWPOINT 0 0 0 1 0 0 0\n"
            f"POINTS {len(points)}\nDATA ascii\n"
        )
        body = "\n".join(f"{x} {y} {z}" for x, y, z in points)
        return header + body

    def publish(self, pcd_data):
        success = publish_kafka_message(
            topic=BLICKFELD_KAFKA_TOPIC,
            value=pcd_data,
            value_serializer=lambda v: v.encode('utf-8')
        )
        if not success:
            print("⚠️ Failed to publish message to Kafka.")

    def run(self):
        # --- ALTERED: Use dummy_connect instead of connect_lidar ---
        _ = self.dummy_connect() # No real scanner object needed for dummy data
        
        print("🟢 Streaming DUMMY point cloud data to Kafka. Press Ctrl+C to stop.")
        while self.running:
            try:
                # --- ALTERED: Use generate_dummy_frame instead of retrieve_frame ---
                points = self.generate_dummy_frame(num_points=500) # You can adjust the number of dummy points
                pcd_data = self.format_pcd(points)
                self.publish(pcd_data)
            except Exception as e:
                print(f"❌ Error: {e}")
            time.sleep(self.sleep)

        print("🛑 Streamer stopped.")


if __name__ == "__main__":
    BlickfeldStreamer().run()